env:
  browser: true
  es2021: true
  'jest/globals': true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'jest'
rules:
  'import/prefer-default-export':
    - off
  'no-underscore-dangle':
    - off
  'import/extensions':
    - off
  'import/no-unresolved':
    - warn
  'camelcase':
    - off
